@startuml



class LoginInterface {
 login(pws:String, userName: String)
 subscribe()
}


class BDDManager {

 checkUser(pws:String, userName: String):boolean
 getParentProfil(userName: String):Parent
}

class ParentManager {

 displayUser(parent: Parent)
 edit(parent: Parent):Parent
 addKid():Kids
 displayReport(kids: Kids):File
 accessActivity(kids: Kids): ActivityManager
}


class KidsManager {

 displayUser(kids: Kids)
 edit(kids: Kids):Kids
}

class Parent {
  firstName: String
  lastName: String
  email: String
  kids[]: Kids

 }


class  Kids {
   firstName: String
   lastName: String
   photoPath: String
   age: int
  }

class SubscribeManager {

  creatProfil(firstName: String, lastName: String, email: String): Parent
}

class ReportManager {

  displayReport(kids: Kids):File
  download(file: File)
  print(file: File)
}

class ReadingManager {

  category[]: Category
  displayCategory(category[]: Category)
  displayStory(category: Category)
  startReading(story: Story)
  stopReading(story: Story): Time
  readAuto(story: Story): Audio
}

class ActivityManager {

}

class WritingManager {

}
class WritingImageManager {
  category[]: Category
  displayCategory(category[]: Category)
  displayImages(category: Category)
  chooseImages(images[]: Image)
  saving(images[]: Image, text: String, kids: Kids): Story
  displayCorection()
  share(story: Story)
  validation(story: Story)
}
class WritingDrawingManager {
  category[]: Category
  chooseTools(): Tools
  chooseImages(images[]: Image)
  saving(image: Image, text: String, kids: Kids): Story
  displayCorrection()
  share(story: Story)
  validation(story: Story)
}
enum Tools {
pen
}
class ValidationManager {

  checkError(text: string): String
}
class Story {

  String imagesPath[]
  text: String
}
class Category {
  stories[]: Story
}

SubscribeManager <- LoginInterface
ActivityManager <|-down- WritingManager
ActivityManager <|-down- ReadingManager
WritingManager <|-down- WritingDrawingManager
WritingManager <|- WritingImageManager
ValidationManager <- WritingManager
Category *-left- Story
Parent *-left- Kids
Story <- BDDManager
Category <- BDDManager
Parent <- BDDManager
Kids <- BDDManager
ReportManager <--right- ParentManager
BDDManager <- ActivityManager
BDDManager <-up- parentManager
BDDManager <--down- LoginInterface
BDDManager <--up- KidsManager
ActivityManager <- ParentManager
KidsManager <-left- ParentManager

@enduml
