language: android
android: 
  components: 
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22
    - extra-google-google_play_services
  licenses: 
    - android-sdk-license-.+
    - google-gdk-license-.+
sudo: required
before_script: 
  - "android update sdk --no-ui --filter build-tools-24.0.1,android-24,extra-android-m2repository"
  - "echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a"
before_install: 
  - "chmod +x gradlew"
jdk: oraclejdk8
script: 
  - "./gradlew build connectedCheck --stacktrace"
  
